#### ============== nextstrain analysis configuration file ============== ####

# Author: Will Hannon

#### ------------------------- Accessions ------------------------ ####

accessions:
  all: data/sequences.acc
  library: MW473668.1
  reference: NC_004162.2
  outgroup: NC_075006.1

#### ------------------------- Parameters ------------------------ ####

feature: structural polyprotein

filter:
  min_genome_size: 0
  max_genome_size: 15000
  min_feature_size: 0
  max_feature_size: 15000
  min_genome_ambiguity: 1
  min_feature_ambiguity: 1
  min_alignment_score: 0
  remove_duplicates: false

#### -------------------------- Directories ------------------------- ####

sequence_dir: results/sequences
log_dir: results/logs