#### ============== nextstrain analysis configuration file ============== ####

# Author: Will Hannon

#### ------------------------- Accessions ------------------------ ####

accessions:
  all: data/sequences.acc
  include: data/include.acc
  library: MW473668.1
  outgroup: NC_075006.1

#### ------------------------- Parameters ------------------------ ####

outgroup:
  accession: NC_075006.1
  strain: SG650_NC_075006

feature: structural polyprotein
name: CHIKVgp2
genes:
  "CHIKVgp2": "CHIKVgp2"
  "capsid_protein": "Capsid"
  "E3_protein": "E3"
  "E2_envelope_glycoprotein": "E2"
  "6K_protein": "6K"
  "E1_envelope_glycoprotein": "E1"

filter:
  min_feature_length: 3647
  max_feature_length: 3847
  max_ambiguous_positions: 0
  remove_duplicates: "False"
  min_alignment_score: 35 
  remove_partial: "True"
  remove_incomplete: "True"

virus: "CHIKV"

country_mapping:
  "Cote d'ivoire": "Ivory Coast"
  "Borneo": "Indonesia"

host_mapping:
  "male patient": "Homo sapiens"
  "Aedes aegypti (mosquito)": "Aedes aegypti"
  "Anopheles (Ceilia) funestus": "Anopheles funestus"
  "mosquito" : Mosquito
  "sentinel mouse" : Mouse

inferred_traits:
  - lineage
  - subregion

color:
  scheme: configuration/color-schemes.tsv
  traits:
    - host
    - lineage
    - region
    - subregion
    - country
  ordering:
    "country": "region"
    "subregion": "region"

auspice:
  config: configuration/auspice-config.json
  coordinates: configuration/coordinates.tsv
  title: "'CHIKV structural glycoprotein'"
  description: ""

#### -------------------------- Directories ------------------------- ####

reference_dir: results/references
sequence_dir: results/sequences
metadata_dir: results/metadata
notebook_dir: results/notebooks
align_dir: results/alignments
tree_dir: results/tree
auspice_dir: auspice/
log_dir: results/logs