#### ============== snakemake configuration file ============== ####

# Configuration file for CHIKV library quality analysis
# Author: William Hannon

#### ------------------------- Samples ------------------------ ####

runs: data/library_runs.csv

#### -------------------------- Dirs ------------------------- ####

data_dir: data
gene_dir: results/gene_sequence

#### ------------------------ Parameters ----------------------- ####

max_ccs_error_rate: 1.0e-4  # only keep CCS if gene/barcode error rate <= this
consensus_params:  # parameters for building PacBio consensus sequences
  max_sub_diffs: null
  max_indel_diffs: null
  max_minor_sub_frac: 1
  max_minor_indel_frac: 1
  min_support: 1

mutation_design_classification:
  csv: data/mutation_design_classification.csv # CSV with data
  site_col: sequential_site # site column, should be reference_site or sequential_site

site_numbering_map: data/site_numbering_map.csv

# Created file with barcode-variant lookup table
codon_variants: results/variants/codon_variants.csv