executor: slurm
latency-wait: 60
jobs: 100
slurm-init-seconds-before-status-checks: 20

default-resources:
  slurm_account: bloom_j
  partition: campus-new
  runtime: 10800
  cpus_per_task: 1
  mem_mb: 4000

set-resources:
  fetch_sra_to_fastq_pe:
    cpus_per_task: 4
  fetch_sra_to_fastq_se:
    cpus_per_task: 4
  align_with_minimap:
    cpus_per_task: 4
  trim_all_reads_pe:
    cpus_per_task: 4
  trim_all_reads_se:
    cpus_per_task: 4
  filter_viral_reads_w_bbduk_pe:
    cpus_per_task: 4
  filter_viral_reads_w_bbduk_se:
    cpus_per_task: 4