name: intrahost
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - jupyterlab
  - pandas=2.2
  - altair=5.5
  - biopython=1.84
  - bcbio-gff=0.7.1
  - snakemake=8.25.3
  - snakemake-executor-plugin-slurm
  - pysam
  - kingfisher
  - sra-tools
  - samtools>=1.20
  - minimap2=2.28
  - bbmap=39.19
  - bioconda:ivar=1.4.3
  - bwa
  - fastp
  - seqtk
  - pip